// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yezfxbkztpbckusampie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllemZ4Ymt6dHBiY2t1c2FtcGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTEwMDYsImV4cCI6MjA3MjMyNzAwNn0.DDGxddif07QgOfqvxc-ibR0_Mj00G1vU_AhNUr8rfto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});